package com.worldline.sips.model;

public enum PaymentMeanBrand {
    AMEX, BCMC, CB, CBCONLINE, ELV, IDEAL, IGNHOMEPAY, KBCONLINE, MAESTRO, MASTERCARD, MASTERPASS, PAYPAL, PAYTRAIL, SOFORTUBERWEISUNG, VISA, VPAY
}
